version: "3.8"
services:
  frontend:
    build: ./frontend
    image: listerical_fe:latest
    stdin_open: true
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BE_URL=http://13.94.236.228:5000
  backend:
    build: ./backend
    image: listerical_be:latest
    ports:
      - "5000:5000" # delete in prod
    environment:
      - HOST=db
      - USER=root
      - PASSWORD=12345
      - DATABASE=listerical_db
      - NODE_ENV=production
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306" #delete in prod
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=listerical_db
